name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: One-sentence bug summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
