name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: input
    id: problem
    attributes:
      label: Problem statement
      placeholder: What user problem should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe the expected behavior.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
